# Get's the data and manipulates it in the right form
# install.packages("plyr") # if not done
# install.packages("reshape2") # if not done
library(plyr)
library(reshape2)
setwd("C:/Users/Timo/Google Drive/Marta/data")
data <- read.csv("C:/Users/Timo/Google Drive/Marta/data/data.csv", header=T)
names(data) <- c("country",
                "countrycode",
                "variable",
                "varcode",
                "95Q1",
                "95Q2",
                "95Q3",
                "95Q4",
                "96Q1",
                "96Q2",
                "96Q3",
                "96Q4",
                "97Q1",
                "97Q2",
                "97Q3",
                "97Q4",
                "98Q1",
                "98Q2",
                "98Q3",
                "98Q4",
                "99Q1",
                "99Q2",
                "99Q3",
                "99Q4",
                "00Q1",
                "00Q2",
                "00Q3",
                "00Q4",
                "01Q1",
                "01Q2",
                "01Q3",
                "01Q4",
                "02Q1",
                "02Q2",
                "02Q3",
                "02Q4",
                "03Q1",
                "03Q2",
                "03Q3",
                "03Q4",
                "04Q1",
                "04Q2",
                "04Q3",
                "04Q4",
                "05Q1",
                "05Q2",
                "05Q3",
                "05Q4",
                "06Q1",
                "06Q2",
                "06Q3",
                "06Q4",
                "07Q1",
                "07Q2",
                "07Q3",
                "07Q4",
                "08Q1",
                "08Q2",
                "08Q3",
                "08Q4",
                "09Q1",
                "09Q2",
                "09Q3",
                "09Q4",
                "10Q1",
                "10Q2",
                "10Q3",
                "10Q4",
                "11Q1",
                "11Q2",
                "11Q3",
                "11Q4",
                "12Q1",
                "12Q2",
                "12Q3",
                "12Q4",
                "13Q1",
                "13Q2",
                "13Q3",
                "13Q4",
                "14Q1",
                "14Q2",
                "14Q3",
                "14Q4")
data$id <- c(as.factor(data$country))
data2 <- melt(data, id = c(1,2,3,4,85))
names(data2)[6] <- "year"
data3 <- dcast(data2,country + countrycode + id + year ~ variable)
write.csv(data3, "c:/users/timo/google drive/marta/data/orgdata.csv")
